version: '3.7'
services:
  excalidraw:
    image: cavia/excalidraw:latest
    restart: always
    ports:
      - 8080:80
    container_name: excalidraw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kroki:
    image: yuzutech/kroki
    restart: always
    container_name: kroki
    ports:
      - 8000:8000
    env_file: envs/kroki.env
    depends_on:
      - blockdiag
      - mermaid
      - bpmn
      - excalidraw-kroki
      - wireviz

  blockdiag:
    image: yuzutech/kroki-blockdiag
    container_name: blockdiag
    restart: always

  mermaid:
    image: yuzutech/kroki-mermaid
    container_name: mermaid
    restart: always

  bpmn:
    image: yuzutech/kroki-bpmn
    container_name: bpmn
    restart: always

  excalidraw-kroki:
    image: yuzutech/kroki-excalidraw
    container_name: excalidraw-kroki
    restart: always

  wireviz:
    image: yuzutech/kroki-wireviz
    container_name: wireviz
    restart: always

  db-joplin:
    image: postgres:15
    volumes:
      - data-postgres-joplin:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: envs/db-joplin.env

  joplin:
    image: florider89/joplin-server:latest
    depends_on:
      - db-joplin
    ports:
      - "22300:22300"
    restart: unless-stopped
    env_file: envs/joplin.env
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    env_file: 
      - ./mealie.env
    volumes:
      - data-mealie:/app/data
  monica-app:
    image: monica
    container_name: monica-app
    ports:
      - 8081:80
    depends_on:
      - monica-db
    env_file:
      - envs/monica.env
    volumes:
      - data-monica:/var/www/html/storage

  monica-db:
    image: mysql:5.7
    container_name: monica-db
    env_file:
      - envs/monica-db.env
    volumes:
      - mysql-monica:/var/lib/mysql

  openproject:
    image: openproject/community:12
    container_name: openproject
    ports:
      - 8080:80
    env_file:
      - envs/openproject.env
    volumes:
      - data-openproject-pgdata:/var/openproject/pgdata
      - data-openproject-assets:/var/openproject/assets
    restart: always

  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data-nginx:/var/www/nginx
      - config-nginx:/etc/nginx/conf.d/
    depends_on:
      - excalidraw
      - joplin
      - kroki
      - mealie
      - monica-app
      - openproject
volumes:
  data-nginx:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/nginx
  config-nginx:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config/nginx
  data-postgres-joplin:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/postgres-joplin
  data-mealie:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/mealie
  data-monica:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/monica
  mysql-monica:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/mysql-monica
  data-openproject-pgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/openproject-pgdata
  data-openproject-assets:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/openproject-assets