version: '3.7'
services:
  excalidraw:
    image: cavia/excalidraw:latest
    restart: always
    ports:
      - 8080:80
    container_name: excalidraw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kroki:
    image: yuzutech/kroki
    restart: always
    container_name: kroki
    ports:
      - 8000:8000
    env_file: envs/kroki.env
    depends_on:
      - blockdiag
      - mermaid
      - bpmn
      - excalidraw-kroki
      - wireviz

  blockdiag:
    image: yuzutech/kroki-blockdiag
    container_name: blockdiag
    restart: always

  mermaid:
    image: yuzutech/kroki-mermaid
    container_name: mermaid
    restart: always

  bpmn:
    image: yuzutech/kroki-bpmn
    container_name: bpmn
    restart: always

  excalidraw-kroki:
    image: yuzutech/kroki-excalidraw
    container_name: excalidraw-kroki
    restart: always

  wireviz:
    image: yuzutech/kroki-wireviz
    container_name: wireviz
    restart: always
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data/nginx:/var/www/nginx
      - config/nginx:/etc/nginx/conf.d/
    depends_on:
      - excalidraw
volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
  config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config
